version: "3"
services: 
    alpine-nginx:
        image: alpine-nginx
        ports:
            - "80:80"
        volumes: 
            - ./config/nginx.conf:/etc/nginx/nginx.conf
            - ./config/sub.conf:/etc/php7/php-fpm.d/sub.conf
            - ./config/php.ini:/etc/php7/conf.d/php.ini
            - ./config/default.conf:/etc/nginx/conf.d/default.conf
            - ${WEB_DOCUMENT_DIR}:/var/www/practice
            - ./devtools/composer.json:/devtools/composer.json
            - ./config/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
        command: ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
        stdin_open: true
        tty: true
        container_name: alpine-nginx
    
    mysql:
        image: mysql:8.0
        environment:
            TZ: "Asia/Tokyo"
            MYSQL_ROOT_PASSWORD: root_pass
            MYSQL_DATABASE: test_db
            MYSQL_USER: test
            MYSQL_PASSWORD: test
        volumes:
            - ./mysql:/var/lib/mysql
        ports:
            - 3306:3306
        container_name: db_host
